deployment

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -7,7 +7,7 @@ on:
 env:
       IMAGE_NAME: bouthainabakouch/backend-api
       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
-
+      BUILD_NUMBER: ${{ github.run_number }}
 jobs:
 
   test:
@@ -64,20 +64,27 @@ jobs:
                 *🔗 Commit Link:* https://github.com/${{ github.repository }}/commit/${{ github.sha }}
                 *🔗 Actions Run:* https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
 
-                ---
-                _(This message was automatically generated by GitHub Actions)_
-
-
-
   build-and-push:
+
     runs-on: ubuntu-latest
     needs: test
     steps:
+
+      - name: Notify Build Start
+        uses: act10ns/slack@v2
+        with:
+            status: starting
+            message: |
+                    *Docker Build Started*
+                    Building image ${{ env.IMAGE_NAME }}
+                    Branch: ${{ github.ref }}
+                    Run Number: ${{ env.BUILD_NUMBER }}
       - name: checkout
         uses: actions/checkout@v4
 
       - name: build docker image
-        run: docker build -t ${{ env.IMAGE_NAME}} .
+        id: build
+        run: docker build -t ${{ env.IMAGE_NAME}} . || echo "::set-output name=status::failure"
         
       - name: login to dockerhub
         uses: docker/login-action@v3
@@ -85,32 +92,66 @@ jobs:
             username: ${{ vars.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: push image docker
-        run: docker push ${{ env.IMAGE_NAME}}:latest
-        
       - name: tag image With version number
         run: docker tag ${{ env.IMAGE_NAME}} ${{ env.IMAGE_NAME}}:${{ github.run_number }}
 
       - name: push image with version number
         run: docker push ${{ env.IMAGE_NAME}}:${{ github.run_number }}
+      
+      - name: push image docker
+        run: docker push ${{ env.IMAGE_NAME}}:latest
 
+      - name: Notify Build Results
+        if: always()
+        uses: act10ns/slack@v2
+        with:
+          status: ${{ steps.build.outputs.status || job.status }}
+          message: |
+            *Docker Build Results* (${{ job.status }})
+            Image: ${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }}
+            ${{ steps.build.outputs.status == 'failure' && '❌ Build failed!' || '✔️ Build succeeded!' }}
+            ${{ steps.build.outputs.status == 'failure' && 'Check the workflow run for build errors.' || 'Image successfully pushed to Docker Hub.' }}
 
   deployement:
+
     runs-on: ubuntu-latest
     needs: build-and-push
     steps:
-          - name: connect via ssh and execute commands
-            uses: appleboy/ssh-action@v1
-            with:
-                  host: ${{ secrets.HOST }}
-                  username: user
-                  password: ${{ secrets.PASSWORD }}
-                  script: |
-                      cd /home/user/devops-proj/back
-                      sudo git pull
-                      sudo docker compose pull
-                      sudo docker compose up -d --force-recreate --remove-orphans
-                      
+          
+      - name: Notify Deployment Start
+        uses: act10ns/slack@v2
+        with:
+          status: starting
+          message: |
+            *Starting Deployment*
+            Version: ${{ env.BUILD_NUMBER }}
+            Environment: Development
+
+      - name: connect via ssh and execute commands
+        id: deploy
+        uses: appleboy/ssh-action@v1
+        with:
+              host: ${{ secrets.HOST }}
+              username: user
+              password: ${{ secrets.PASSWORD }}
+              script: |
+                    cd /home/user/devops-proj/back
+                    sudo git pull
+                    sudo docker compose pull
+                    sudo docker compose up -d --force-recreate --remove-orphans || exit 1
+
+      - name: Notify Deployment Results
+        if: always()
+        uses: act10ns/slack@v2
+        with:
+          status: ${{ steps.deploy.outcome == 'failure' && 'failure' || 'success' }}
+          message: |
+                *Deployment Results* (${{ job.status }})
+                Version: ${{ env.BUILD_NUMBER }}
+                ${{ steps.deploy.outcome == 'failure' && '❌ Deployment failed!' || '✔️ Deployment succeeded!' }}
+                ${{ steps.deploy.outcome == 'failure' && 'Check the workflow run for deployment errors.' || 'Application successfully deployed!' }}
+                    
+                
 
 
 
